/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ClienteApp from '../model/ClienteApp';

/**
* ClienteAppController service.
* @module api/ClienteAppControllerApi
* @version v0
*/
export default class ClienteAppControllerApi {

    /**
    * Constructs a new ClienteAppControllerApi. 
    * @alias module:api/ClienteAppControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the actualizarCliente operation.
     * @callback module:api/ClienteAppControllerApi~actualizarClienteCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Actualizar cliente
     * Actualiza los datos de un cliente existente
     * @param {String} nifCif NIF/CIF del cliente a actualizar
     * @param {module:model/ClienteApp} clienteApp Datos del cliente a actualizar
     * @param {module:api/ClienteAppControllerApi~actualizarClienteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    actualizarCliente(nifCif, clienteApp, callback) {
      let postBody = clienteApp;
      // verify the required parameter 'nifCif' is set
      if (nifCif === undefined || nifCif === null) {
        throw new Error("Missing the required parameter 'nifCif' when calling actualizarCliente");
      }
      // verify the required parameter 'clienteApp' is set
      if (clienteApp === undefined || clienteApp === null) {
        throw new Error("Missing the required parameter 'clienteApp' when calling actualizarCliente");
      }

      let pathParams = {
        'nifCif': nifCif
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/clientes/actualizarcliente/{nifCif}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the buscarPorFiltros1 operation.
     * @callback module:api/ClienteAppControllerApi~buscarPorFiltros1Callback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ClienteApp>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Buscar clientes
     * Busca clientes según filtros exactos seleccionados
     * @param {module:model/ClienteApp} clienteApp Filtros de búsqueda exacta por atributos (tipoCliente, nifCif, estadoCliente...)
     * @param {module:api/ClienteAppControllerApi~buscarPorFiltros1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ClienteApp>}
     */
    buscarPorFiltros1(clienteApp, callback) {
      let postBody = clienteApp;
      // verify the required parameter 'clienteApp' is set
      if (clienteApp === undefined || clienteApp === null) {
        throw new Error("Missing the required parameter 'clienteApp' when calling buscarPorFiltros1");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = [ClienteApp];
      return this.apiClient.callApi(
        '/api/clientes/buscarporfiltros', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the buscarPorNombre1 operation.
     * @callback module:api/ClienteAppControllerApi~buscarPorNombre1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/ClienteApp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Buscar clientes por nombre
     * Busca clientes por coincidencia parcial de nombre
     * @param {String} nombre Texto del nombre a buscar
     * @param {module:api/ClienteAppControllerApi~buscarPorNombre1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClienteApp}
     */
    buscarPorNombre1(nombre, callback) {
      let postBody = null;
      // verify the required parameter 'nombre' is set
      if (nombre === undefined || nombre === null) {
        throw new Error("Missing the required parameter 'nombre' when calling buscarPorNombre1");
      }

      let pathParams = {
      };
      let queryParams = {
        'nombre': nombre
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ClienteApp;
      return this.apiClient.callApi(
        '/api/clientes/buscar/nombre', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the cambiarNif operation.
     * @callback module:api/ClienteAppControllerApi~cambiarNifCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cambiar NIF/CIF de un cliente
     * Migra todos los datos de un cliente a un nuevo NIF/CIF
     * @param {String} nifViejo 
     * @param {String} nifNuevo 
     * @param {module:api/ClienteAppControllerApi~cambiarNifCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    cambiarNif(nifViejo, nifNuevo, callback) {
      let postBody = null;
      // verify the required parameter 'nifViejo' is set
      if (nifViejo === undefined || nifViejo === null) {
        throw new Error("Missing the required parameter 'nifViejo' when calling cambiarNif");
      }
      // verify the required parameter 'nifNuevo' is set
      if (nifNuevo === undefined || nifNuevo === null) {
        throw new Error("Missing the required parameter 'nifNuevo' when calling cambiarNif");
      }

      let pathParams = {
      };
      let queryParams = {
        'nifViejo': nifViejo,
        'nifNuevo': nifNuevo
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/clientes/cambiar-nif', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the cierreEjercicio operation.
     * @callback module:api/ClienteAppControllerApi~cierreEjercicioCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cierre de ejercicio
     * Mueve todos los clientes a histórico y actualiza casilla505
     * @param {module:api/ClienteAppControllerApi~cierreEjercicioCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    cierreEjercicio(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/clientes/cierre-ejercicio', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the crearCliente operation.
     * @callback module:api/ClienteAppControllerApi~crearClienteCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Crear cliente
     * Crea un nuevo cliente en la base de datos
     * @param {module:model/ClienteApp} clienteApp Datos del cliente a crear
     * @param {module:api/ClienteAppControllerApi~crearClienteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    crearCliente(clienteApp, callback) {
      let postBody = clienteApp;
      // verify the required parameter 'clienteApp' is set
      if (clienteApp === undefined || clienteApp === null) {
        throw new Error("Missing the required parameter 'clienteApp' when calling crearCliente");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/clientes/crearcliente', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the eliminarCliente1 operation.
     * @callback module:api/ClienteAppControllerApi~eliminarCliente1Callback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Eliminar cliente
     * Elimina un cliente por su NIF/CIF
     * @param {String} nifCif NIF/CIF del cliente a eliminar
     * @param {module:api/ClienteAppControllerApi~eliminarCliente1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    eliminarCliente1(nifCif, callback) {
      let postBody = null;
      // verify the required parameter 'nifCif' is set
      if (nifCif === undefined || nifCif === null) {
        throw new Error("Missing the required parameter 'nifCif' when calling eliminarCliente1");
      }

      let pathParams = {
        'nifCif': nifCif
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/clientes/eliminarcliente/{nifCif}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the eliminarTodos operation.
     * @callback module:api/ClienteAppControllerApi~eliminarTodosCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Eliminar todos los clientes
     * Elimina todos los clientes de la base de datos. Solo para testing.
     * @param {module:api/ClienteAppControllerApi~eliminarTodosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    eliminarTodos(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/clientes/todos', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the obtenerCliente1 operation.
     * @callback module:api/ClienteAppControllerApi~obtenerCliente1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/ClienteApp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener cliente
     * Obtiene un cliente por su NIF/CIF
     * @param {String} nifCif NIF/CIF del cliente
     * @param {module:api/ClienteAppControllerApi~obtenerCliente1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClienteApp}
     */
    obtenerCliente1(nifCif, callback) {
      let postBody = null;
      // verify the required parameter 'nifCif' is set
      if (nifCif === undefined || nifCif === null) {
        throw new Error("Missing the required parameter 'nifCif' when calling obtenerCliente1");
      }

      let pathParams = {
        'nifCif': nifCif
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ClienteApp;
      return this.apiClient.callApi(
        '/api/clientes/obtenerpornif/{nifCif}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the obtenerTodos1 operation.
     * @callback module:api/ClienteAppControllerApi~obtenerTodos1Callback
     * @param {String} error Error message, if any.
     * @param {module:model/ClienteApp} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener todos los clientes
     * Devuelve la lista completa de clientes
     * @param {module:api/ClienteAppControllerApi~obtenerTodos1Callback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClienteApp}
     */
    obtenerTodos1(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ClienteApp;
      return this.apiClient.callApi(
        '/api/clientes/obtenerTodos', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
