/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ClienteAppHistorico from '../model/ClienteAppHistorico';

/**
* ClienteAppHistoricoController service.
* @module api/ClienteAppHistoricoControllerApi
* @version v0
*/
export default class ClienteAppHistoricoControllerApi {

    /**
    * Constructs a new ClienteAppHistoricoControllerApi. 
    * @alias module:api/ClienteAppHistoricoControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the buscarPorFiltros operation.
     * @callback module:api/ClienteAppHistoricoControllerApi~buscarPorFiltrosCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ClienteAppHistorico>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Buscar clientes
     * Busca clientes en el historico según filtros exactos seleccionados
     * @param {module:model/ClienteAppHistorico} clienteAppHistorico Filtros de búsqueda exacta por atributos (tipoCliente, nifCif, estadoCliente...)
     * @param {module:api/ClienteAppHistoricoControllerApi~buscarPorFiltrosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/ClienteAppHistorico>}
     */
    buscarPorFiltros(clienteAppHistorico, callback) {
      let postBody = clienteAppHistorico;
      // verify the required parameter 'clienteAppHistorico' is set
      if (clienteAppHistorico === undefined || clienteAppHistorico === null) {
        throw new Error("Missing the required parameter 'clienteAppHistorico' when calling buscarPorFiltros");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = [ClienteAppHistorico];
      return this.apiClient.callApi(
        '/api/clientesHistorico/buscar', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the buscarPorNombre operation.
     * @callback module:api/ClienteAppHistoricoControllerApi~buscarPorNombreCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ClienteAppHistorico} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Buscar clientes en el historico por nombre
     * Busca clientes por coincidencia parcial de nombre
     * @param {String} nombre Nombre a buscar
     * @param {module:api/ClienteAppHistoricoControllerApi~buscarPorNombreCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClienteAppHistorico}
     */
    buscarPorNombre(nombre, callback) {
      let postBody = null;
      // verify the required parameter 'nombre' is set
      if (nombre === undefined || nombre === null) {
        throw new Error("Missing the required parameter 'nombre' when calling buscarPorNombre");
      }

      let pathParams = {
      };
      let queryParams = {
        'nombre': nombre
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ClienteAppHistorico;
      return this.apiClient.callApi(
        '/api/clientesHistorico/buscar/nombre', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the eliminarCliente operation.
     * @callback module:api/ClienteAppHistoricoControllerApi~eliminarClienteCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Eliminar cliente historico
     * Elimina un cliente del historico por su NIF/CIF
     * @param {String} nifCif NIF/CIF del cliente a eliminar
     * @param {module:api/ClienteAppHistoricoControllerApi~eliminarClienteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    eliminarCliente(nifCif, callback) {
      let postBody = null;
      // verify the required parameter 'nifCif' is set
      if (nifCif === undefined || nifCif === null) {
        throw new Error("Missing the required parameter 'nifCif' when calling eliminarCliente");
      }

      let pathParams = {
        'nifCif': nifCif
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/clientesHistorico/borrarcliente/{nifCif}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the eliminarTodosClientes operation.
     * @callback module:api/ClienteAppHistoricoControllerApi~eliminarTodosClientesCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Elimina todos los clientes del historico
     * Elimina todos los clientes del historico
     * @param {module:api/ClienteAppHistoricoControllerApi~eliminarTodosClientesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    eliminarTodosClientes(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/api/clientesHistorico/eliminartodos', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the obtenerCliente operation.
     * @callback module:api/ClienteAppHistoricoControllerApi~obtenerClienteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ClienteAppHistorico} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener cliente
     * Obtener un cliente mediante su Nif/Cif
     * @param {String} nifCif 
     * @param {module:api/ClienteAppHistoricoControllerApi~obtenerClienteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClienteAppHistorico}
     */
    obtenerCliente(nifCif, callback) {
      let postBody = null;
      // verify the required parameter 'nifCif' is set
      if (nifCif === undefined || nifCif === null) {
        throw new Error("Missing the required parameter 'nifCif' when calling obtenerCliente");
      }

      let pathParams = {
        'nifCif': nifCif
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ClienteAppHistorico;
      return this.apiClient.callApi(
        '/api/clientesHistorico/buscarcliente/{nifCif}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the obtenerClientes operation.
     * @callback module:api/ClienteAppHistoricoControllerApi~obtenerClientesCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ClienteAppHistorico} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Obtener todos los clientes
     * Devuelve la lista completa de clientes en el historico
     * @param {module:api/ClienteAppHistoricoControllerApi~obtenerClientesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ClienteAppHistorico}
     */
    obtenerClientes(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = ClienteAppHistorico;
      return this.apiClient.callApi(
        '/api/clientesHistorico', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
