/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ExcelImportResponseDTO from '../model/ExcelImportResponseDTO';

/**
* ExcelController service.
* @module api/ExcelControllerApi
* @version v0
*/
export default class ExcelControllerApi {

    /**
    * Constructs a new ExcelControllerApi. 
    * @alias module:api/ExcelControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the importar operation.
     * @callback module:api/ExcelControllerApi~importarCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ExcelImportResponseDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Importar clientes desde Excel
     * Lee un archivo .xlsx y crea los clientes en la base de datos
     * @param {File} file 
     * @param {module:api/ExcelControllerApi~importarCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ExcelImportResponseDTO}
     */
    importar(file, callback) {
      let postBody = null;
      // verify the required parameter 'file' is set
      if (file === undefined || file === null) {
        throw new Error("Missing the required parameter 'file' when calling importar");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
        'file': file
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['multipart/form-data'];
      let accepts = ['*/*'];
      let returnType = ExcelImportResponseDTO;
      return this.apiClient.callApi(
        '/api/clientes/excel/importar', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
