/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CambioPasswordDTO from '../model/CambioPasswordDTO';
import UsuarioActualizarDTO from '../model/UsuarioActualizarDTO';
import UsuarioCreacionDTO from '../model/UsuarioCreacionDTO';
import UsuarioRespuestaDTO from '../model/UsuarioRespuestaDTO';

/**
* UserController service.
* @module api/UserControllerApi
* @version v0
*/
export default class UserControllerApi {

    /**
    * Constructs a new UserControllerApi. 
    * @alias module:api/UserControllerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the actualizar operation.
     * @callback module:api/UserControllerApi~actualizarCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} uid 
     * @param {module:model/UsuarioActualizarDTO} usuarioActualizarDTO 
     * @param {module:api/UserControllerApi~actualizarCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    actualizar(uid, usuarioActualizarDTO, callback) {
      let postBody = usuarioActualizarDTO;
      // verify the required parameter 'uid' is set
      if (uid === undefined || uid === null) {
        throw new Error("Missing the required parameter 'uid' when calling actualizar");
      }
      // verify the required parameter 'usuarioActualizarDTO' is set
      if (usuarioActualizarDTO === undefined || usuarioActualizarDTO === null) {
        throw new Error("Missing the required parameter 'usuarioActualizarDTO' when calling actualizar");
      }

      let pathParams = {
        'uid': uid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/user/actualizarusuario/{uid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the admin operation.
     * @callback module:api/UserControllerApi~adminCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/UserControllerApi~adminCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    admin(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/user/test', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the cambiarPassword operation.
     * @callback module:api/UserControllerApi~cambiarPasswordCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} uid 
     * @param {module:model/CambioPasswordDTO} cambioPasswordDTO 
     * @param {module:api/UserControllerApi~cambiarPasswordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    cambiarPassword(uid, cambioPasswordDTO, callback) {
      let postBody = cambioPasswordDTO;
      // verify the required parameter 'uid' is set
      if (uid === undefined || uid === null) {
        throw new Error("Missing the required parameter 'uid' when calling cambiarPassword");
      }
      // verify the required parameter 'cambioPasswordDTO' is set
      if (cambioPasswordDTO === undefined || cambioPasswordDTO === null) {
        throw new Error("Missing the required parameter 'cambioPasswordDTO' when calling cambiarPassword");
      }

      let pathParams = {
        'uid': uid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/user/actualizarpassword/{uid}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the crearUsuario operation.
     * @callback module:api/UserControllerApi~crearUsuarioCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/UsuarioCreacionDTO} usuarioCreacionDTO 
     * @param {module:api/UserControllerApi~crearUsuarioCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    crearUsuario(usuarioCreacionDTO, callback) {
      let postBody = usuarioCreacionDTO;
      // verify the required parameter 'usuarioCreacionDTO' is set
      if (usuarioCreacionDTO === undefined || usuarioCreacionDTO === null) {
        throw new Error("Missing the required parameter 'usuarioCreacionDTO' when calling crearUsuario");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/user/crearusuario', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the eliminarUsuario operation.
     * @callback module:api/UserControllerApi~eliminarUsuarioCallback
     * @param {String} error Error message, if any.
     * @param {String} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} uid 
     * @param {module:api/UserControllerApi~eliminarUsuarioCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link String}
     */
    eliminarUsuario(uid, callback) {
      let postBody = null;
      // verify the required parameter 'uid' is set
      if (uid === undefined || uid === null) {
        throw new Error("Missing the required parameter 'uid' when calling eliminarUsuario");
      }

      let pathParams = {
        'uid': uid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = 'String';
      return this.apiClient.callApi(
        '/user/eliminarusuario/{uid}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the encontrarPorEmail operation.
     * @callback module:api/UserControllerApi~encontrarPorEmailCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UsuarioRespuestaDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} email 
     * @param {module:api/UserControllerApi~encontrarPorEmailCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UsuarioRespuestaDTO}
     */
    encontrarPorEmail(email, callback) {
      let postBody = null;
      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling encontrarPorEmail");
      }

      let pathParams = {
        'email': email
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = UsuarioRespuestaDTO;
      return this.apiClient.callApi(
        '/user/email/{email}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the encontrarPorId operation.
     * @callback module:api/UserControllerApi~encontrarPorIdCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UsuarioRespuestaDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} uid 
     * @param {module:api/UserControllerApi~encontrarPorIdCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UsuarioRespuestaDTO}
     */
    encontrarPorId(uid, callback) {
      let postBody = null;
      // verify the required parameter 'uid' is set
      if (uid === undefined || uid === null) {
        throw new Error("Missing the required parameter 'uid' when calling encontrarPorId");
      }

      let pathParams = {
        'uid': uid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = UsuarioRespuestaDTO;
      return this.apiClient.callApi(
        '/user/id/{uid}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the encontrarPorNombre operation.
     * @callback module:api/UserControllerApi~encontrarPorNombreCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UsuarioRespuestaDTO} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} nombre 
     * @param {module:api/UserControllerApi~encontrarPorNombreCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UsuarioRespuestaDTO}
     */
    encontrarPorNombre(nombre, callback) {
      let postBody = null;
      // verify the required parameter 'nombre' is set
      if (nombre === undefined || nombre === null) {
        throw new Error("Missing the required parameter 'nombre' when calling encontrarPorNombre");
      }

      let pathParams = {
        'nombre': nombre
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = UsuarioRespuestaDTO;
      return this.apiClient.callApi(
        '/user/nombre/{nombre}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the obtenerTodos operation.
     * @callback module:api/UserControllerApi~obtenerTodosCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/UsuarioRespuestaDTO>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/UserControllerApi~obtenerTodosCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/UsuarioRespuestaDTO>}
     */
    obtenerTodos(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer Auth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = [UsuarioRespuestaDTO];
      return this.apiClient.callApi(
        '/user/todoslosusuarios', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
