/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.ClienteAppControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClienteAppControllerApi', function() {
    describe('actualizarCliente', function() {
      it('should call actualizarCliente successfully', function(done) {
        //uncomment below and update the code to test actualizarCliente
        //instance.actualizarCliente(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buscarPorFiltros1', function() {
      it('should call buscarPorFiltros1 successfully', function(done) {
        //uncomment below and update the code to test buscarPorFiltros1
        //instance.buscarPorFiltros1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buscarPorNombre1', function() {
      it('should call buscarPorNombre1 successfully', function(done) {
        //uncomment below and update the code to test buscarPorNombre1
        //instance.buscarPorNombre1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cambiarNif', function() {
      it('should call cambiarNif successfully', function(done) {
        //uncomment below and update the code to test cambiarNif
        //instance.cambiarNif(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cierreEjercicio', function() {
      it('should call cierreEjercicio successfully', function(done) {
        //uncomment below and update the code to test cierreEjercicio
        //instance.cierreEjercicio(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('crearCliente', function() {
      it('should call crearCliente successfully', function(done) {
        //uncomment below and update the code to test crearCliente
        //instance.crearCliente(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eliminarCliente1', function() {
      it('should call eliminarCliente1 successfully', function(done) {
        //uncomment below and update the code to test eliminarCliente1
        //instance.eliminarCliente1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eliminarTodos', function() {
      it('should call eliminarTodos successfully', function(done) {
        //uncomment below and update the code to test eliminarTodos
        //instance.eliminarTodos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('obtenerCliente1', function() {
      it('should call obtenerCliente1 successfully', function(done) {
        //uncomment below and update the code to test obtenerCliente1
        //instance.obtenerCliente1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('obtenerTodos1', function() {
      it('should call obtenerTodos1 successfully', function(done) {
        //uncomment below and update the code to test obtenerTodos1
        //instance.obtenerTodos1(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
