/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.ClienteAppHistoricoControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ClienteAppHistoricoControllerApi', function() {
    describe('buscarPorFiltros', function() {
      it('should call buscarPorFiltros successfully', function(done) {
        //uncomment below and update the code to test buscarPorFiltros
        //instance.buscarPorFiltros(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('buscarPorNombre', function() {
      it('should call buscarPorNombre successfully', function(done) {
        //uncomment below and update the code to test buscarPorNombre
        //instance.buscarPorNombre(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eliminarCliente', function() {
      it('should call eliminarCliente successfully', function(done) {
        //uncomment below and update the code to test eliminarCliente
        //instance.eliminarCliente(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eliminarTodosClientes', function() {
      it('should call eliminarTodosClientes successfully', function(done) {
        //uncomment below and update the code to test eliminarTodosClientes
        //instance.eliminarTodosClientes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('obtenerCliente', function() {
      it('should call obtenerCliente successfully', function(done) {
        //uncomment below and update the code to test obtenerCliente
        //instance.obtenerCliente(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('obtenerClientes', function() {
      it('should call obtenerClientes successfully', function(done) {
        //uncomment below and update the code to test obtenerClientes
        //instance.obtenerClientes(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
