/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiDefinition);
  }
}(this, function(expect, OpenApiDefinition) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiDefinition.UserControllerApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UserControllerApi', function() {
    describe('actualizar', function() {
      it('should call actualizar successfully', function(done) {
        //uncomment below and update the code to test actualizar
        //instance.actualizar(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('admin', function() {
      it('should call admin successfully', function(done) {
        //uncomment below and update the code to test admin
        //instance.admin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('cambiarPassword', function() {
      it('should call cambiarPassword successfully', function(done) {
        //uncomment below and update the code to test cambiarPassword
        //instance.cambiarPassword(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('crearUsuario', function() {
      it('should call crearUsuario successfully', function(done) {
        //uncomment below and update the code to test crearUsuario
        //instance.crearUsuario(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('eliminarUsuario', function() {
      it('should call eliminarUsuario successfully', function(done) {
        //uncomment below and update the code to test eliminarUsuario
        //instance.eliminarUsuario(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('encontrarPorEmail', function() {
      it('should call encontrarPorEmail successfully', function(done) {
        //uncomment below and update the code to test encontrarPorEmail
        //instance.encontrarPorEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('encontrarPorId', function() {
      it('should call encontrarPorId successfully', function(done) {
        //uncomment below and update the code to test encontrarPorId
        //instance.encontrarPorId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('encontrarPorNombre', function() {
      it('should call encontrarPorNombre successfully', function(done) {
        //uncomment below and update the code to test encontrarPorNombre
        //instance.encontrarPorNombre(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('obtenerTodos', function() {
      it('should call obtenerTodos successfully', function(done) {
        //uncomment below and update the code to test obtenerTodos
        //instance.obtenerTodos(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
