package org.gestoriarr.appgestoriarr.model.enums;

public enum TipoPresentada {
    CONFIRMADOPRESENTARNO,
    CONFIRMADOPRESENTARSIPRESENTADANO,
    CONFIRMADOPRESENTARSIPRESENTADASIENVIADANO,
    CONFIRMADOPRESENTARSIPRESENTADASIENVIADASI
}
