package org.gestoriarr.appgestoriarr.model.enums;

public enum TipoRecogidaDatos {
    FACTURARELLENANO,
    FACTURARELLENASIENVIADANO,
    FACTURARELLENASIENVIADASIFIRMADANO,
    FACTURARELLENASIENVIADASIFIRMADASI
}
